[project]
name = "mgmweb"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "frozen-flask>=1.0.2",
    "markdown>=3.8.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
