top100films = [
{'number': 1, 'title': "The Man with a Movie Camera", "directorandyear": "Dziga Vertov, 1929"},
{'number': 2, 'title': "8 1/2", "directorandyear": "Frederico Fellini, 1963"},
{'number': 3, 'title': "The Godfather: Part II", "directorandyear": "Francis Ford Coppola, 1974"},
{'number': 4, 'title': "2001: A Space Odyssey", "directorandyear": "Stanley Kubrick, 1968"},
{'number': 5, 'title': "The Thief of Bagdad", "directorandyear": "Raoul Walsh, 1924"},
{'number': 6, 'title': "City Lights", "directorandyear": "Charles Chaplin, 1931"},
{'number': 7, 'title': "Playtime", "directorandyear": "Jacques Tati, 1967"},
{'number': 8, 'title': "The Palm Beach Story", "directorandyear": "Preston Sturges, 1942"},
{'number': 9, 'title': "The Third Man", "directorandyear": "Carol Reed, 1949"},
{'number': 10, 'title': "The Godfather", "directorandyear": "Francis Ford Coppola, 1972"},
{'number': 11, 'title': "Raising Arizona", "directorandyear": "Joel & Ethan Coen, 1987"},
{'number': 12, 'title': "Rear Window", "directorandyear": "Alfred Hitchcock, 1954"},
{'number': 13, 'title': "Miller's Crossing", "directorandyear": "Joel & Ethan Coen, 1990"},
{'number': 14, 'title': "Citizen Kane", "directorandyear": "Orson Welles, 1941"},
{'number': 15, 'title': "The Apartment", "directorandyear": "Billy Wilder, 1960"},
{'number': 16, 'title': "The Naked City", "directorandyear": "Jules Dassin, 1948"},
{'number': 17, 'title': "Touch of Evil", "directorandyear": "Orson Welles, 1958"},
{'number': 18, 'title': "Ivan the Terrible, Part One", "directorandyear": "Sergei Eisenstein, 1944"},
{'number': 19, 'title': "Stagecoach", "directorandyear": "John Ford, 1939"},
{'number': 20, 'title': "The Set-Up", "directorandyear": "Robert Wise, 1949"},
{'number': 21, 'title': "The Kid Brother", "directorandyear": "Ted Wilde & J.A. Howe, 1927"},
{'number': 22, 'title': "The Cameraman", "directorandyear": "Buster Keaton, 1928"},
{'number': 23, 'title': "I Am Cuba", "directorandyear": "Mikhail Kalatozov, 1964"},
{'number': 24, 'title': "I Fidanzati", "directorandyear": "Ermanno Olmi, 1963"},
{'number': 25, 'title': "Frenzy", "directorandyear": "Alfred Hitchcock, 1972"},
{'number': 26, 'title': "Punch Drunk Love", "directorandyear": "P.T. Anderson, 2002"},
{'number': 27, 'title': "Scarface", "directorandyear": "Howard Hawks, 1932"},
{'number': 28, 'title': "Mon oncle", "directorandyear": "Jacques Tati, 1958"},
{'number': 29, 'title': "Mean Streets", "directorandyear": "Martin Scorsese, 1973"},
{'number': 30, 'title': "Sunrise: A Song of Two Humans", "directorandyear": "F.W. Murnau, 1927"},
{'number': 31, 'title': "Dead of Night", "directorandyear": "Basil Dearden, Alberto Cavalcanti, Robert Hamer, & Charles Crichton, 1945"},
{'number': 32, 'title': "Barry Lyndon", "directorandyear": "Stanley Kubrick, 1975"},
{'number': 33, 'title': "Thieves' Highway", "directorandyear": "Jules Dassin, 1949"},
{'number': 34, 'title': "A Clockwork Orange", "directorandyear": "Stanley Kubrick, 1971"},
{'number': 35, 'title': "An Autumn Afternoon", "directorandyear": "Yasujiro Ozu, 1962"},
{'number': 36, 'title': "Raw Deal", "directorandyear": "Anthony Mann, 1948"},
{'number': 37, 'title': "The Tales of Hoffmann", "directorandyear": "Michael Powell & Emeric Pressburger, 1951"},
{'number': 38, 'title': "The Body Snatcher", "directorandyear": "Robert Wise, 1945"},
{'number': 39, 'title': "Casablanca", "directorandyear": "Michael Curtiz, 1942"},
{'number': 40, 'title': "Strangers on a Train", "directorandyear": "Alfred Hitchcock, 1951"},
{'number': 41, 'title': "Barton Fink", "directorandyear": "Joel & Ethan Coen, 1991"},
{'number': 42, 'title': "Why We Fight", "directorandyear": "Frank Capra, Anatole Litvak, & Kurt Veiller, 1943-1945 [documentary in seven parts]"},
{'number': 43, 'title': "Animal Crackers", "directorandyear": "Victor Heerman, 1930"},
{'number': 44, 'title': "Daisies", "directorandyear": "Vera Chytilova, 1966"},
{'number': 45, 'title': "Dames", "directorandyear": "Ray Enright, 1934"},
{'number': 46, 'title': "Eraserhead", "directorandyear": "David Lynch, 1977"},
{'number': 47, 'title': "Rushmore", "directorandyear": "Wes Anderson, 1998"},
{'number': 48, 'title': "A Letter to Three Wives", "directorandyear": "Joseph L. Mankiewicz, 1949"},
{'number': 49, 'title': "Pulp Fiction", "directorandyear": "Quentin Tarantino, 1994"},
{'number': 50, 'title': "I Was Born, But...", "directorandyear": "Yasujiro Ozu, 1932"},
{'number': 51, 'title': "Stranger than Paradise", "directorandyear": "Jim Jarmusch, 1984"},
{'number': 52, 'title': "Le Million", "directorandyear": "Rene Clair, 1931"},
{'number': 53, 'title': "Make Way for Tomorrow", "directorandyear": "Leo McCarey, 1937"},
{'number': 54, 'title': "Grindhouse", "directorandyear": "Quentin Tarantino & Robert Rodriguez, 2007"},
{'number': 55, 'title': "Bringing Up Baby", "directorandyear": "Howard Hawks, 1938"},
{'number': 56, 'title': "La dolce vita", "directorandyear": "Frederico Fellini, 1960"},
{'number': 57, 'title': "The General", "directorandyear": "Buster Keaton & Clyde Bruckman, 1927"},
{'number': 58, 'title': "Casino", "directorandyear": "Martin Scorsese, 1995"},
{'number': 59, 'title': "The Killing", "directorandyear": "Stanley Kubrick, 1956"},
{'number': 60, 'title': "Only Angels Have Wings", "directorandyear": "Howard Hawks, 1939"},
{'number': 61, 'title': "Spies", "directorandyear": "Fritz Lang, 1928"},
{'number': 62, 'title': "Journey into Fear", "directorandyear": "Norman Foster & Orson Welles, 1943"},
{'number': 63, 'title': "The Lady from Shanghai", "directorandyear": "Orson Welles, 1947"},
{'number': 64, 'title': "Tokyo Story", "directorandyear": "Yasujiro Ozu, 1953"},
{'number': 65, 'title': "The White Sheik", "directorandyear": "Federico Fellini, 1952"},
{'number': 66, 'title': "The Conversation", "directorandyear": "Francis Ford Coppola, 1974"},
{'number': 67, 'title': "The Virgin Spring", "directorandyear": "Ingmar Bergman, 1960"},
{'number': 68, 'title': "Dr. Strangelove", "directorandyear": "Stanley Kubrick, 1964"},
{'number': 69, 'title': "The Good Fairy", "directorandyear": "William Wyler, 1935"},
{'number': 70, 'title': "The Killing of a Chinese Bookie", "directorandyear": "John Cassavetes, 1976"},
{'number': 71, 'title': "Metropolis", "directorandyear": "Fritz Lang, 1927"},
{'number': 72, 'title': "The Best Years of Our Lives", "directorandyear": "William Wyler, 1946"},
{'number': 73, 'title': "Woodstock", "directorandyear": "Michael Wadleigh, 1970"},
{'number': 74, 'title': "Annie Hall", "directorandyear": "Woody Allen, 1977"},
{'number': 75, 'title': "The Big Combo", "directorandyear": "Joseph H. Lewis, 1955"},
{'number': 76, 'title': "The Man Who Wasn't There", "directorandyear": "Joel & Ethan Coen, 2001"},
{'number': 77, 'title': "Lawrence of Arabia", "directorandyear": "David Lean, 1962"},
{'number': 78, 'title': "The Manchurian Candidate", "directorandyear": "John Frankenheimer, 1962"},
{'number': 79, 'title': "Unfaithfully Yours", "directorandyear": "Preston Sturges, 1948"},
{'number': 80, 'title': "The Searchers", "directorandyear": "John Ford, 1956"},
{'number': 81, 'title': "The Gold Rush", "directorandyear": "Charles Chaplin, 1925"},
{'number': 82, 'title': "The Good, the Bad and the Ugly", "directorandyear": "Sergio Leone, 1966"},
{'number': 83, 'title': "Vernon, Florida", "directorandyear": "Errol Morris, 1981"},
{'number': 84, 'title': "A Face in the Crowd", "directorandyear": "Elia Kazan, 1957"},
{'number': 85, 'title': "The Night of the Hunter", "directorandyear": "Charles Laughton, 1955"},
{'number': 86, 'title': "Fail-Safe", "directorandyear": "Sidney Lumet, 1964"},
{'number': 87, 'title': "Ball of Fire", "directorandyear": "Howard Hawks, 1941"},
{'number': 88, 'title': "Koyaanisqatsi", "directorandyear": "Godfrey Reggio, 1982"},
{'number': 89, 'title': "Midnight", "directorandyear": "Mitchell Liesen, 1939"},
{'number': 90, 'title': "The Man Who Laughs", "directorandyear": "Paul Leni, 1928"},
{'number': 91, 'title': "Carrie", "directorandyear": "Brian De Palma, 1976"},
{'number': 92, 'title': "Brand Upon the Brain!", "directorandyear": "Guy Maddin, 2006"},
{'number': 93, 'title': "The Tenant", "directorandyear": "Roman Polanski, 1976"},
{'number': 94, 'title': "WALL-E", "directorandyear": "Andrew Stanton, 2008"},
{'number': 95, 'title': "The Hudsucker Proxy", "directorandyear": "Joel & Ethan Coen, 1994"},
{'number': 96, 'title': "The Bad Sleep Well", "directorandyear": "Akira Kurosawa, 1960"},
{'number': 97, 'title': "The Singing Detective", "directorandyear": "Jon Amiel, 1986 [Miniseries]"},
{'number': 98, 'title': "Being John Malkovich", "directorandyear": "Spike Jonze, 1999"},
{'number': 99, 'title': "Drole de Drame", "directorandyear": "Marcel Carne, 1937"},
{'number': 100, 'title': "The Falls", "directorandyear": "Peter Greenaway, 1980"}]
