splash_descriptions = {
    'default': {'img': '/static/lobster.png',
                'summary': ["Hey. This is Mark Mollineaux, speaking at the behest of the Mark Mollineaux website.",
                            "",
                            "",
                            "I'm currently a PhD Candidate at Stanford University.",
                            "",
                            "This site contains things I've done.",
                            "",
                            "",
                            "Check out my <a href=\"//github.com/bufordsharkley/\">github</a> or <a href=\"//twitter.com/bufordsharkley/\">twitter</a>. No linkedin, because linkedin is spam, and pretty gross."]},
    'drawings': {'img': '/static/lobster.png',
                'summary': ['Drawings and sketches, 2001-present.',"","","The medium is ballpoint pen and notebook paper."]},
    'filmlists': {'img': '/static/lobster.png',
                'summary': ["Some personal lists about film.",
                            "",
                            "",
                            "A top 100 list, and links to software I developed for tracking film canons."]},
    'etc': {'img': '/static/lobster.png',
                'summary': ["Odds and ends.", "", "Doggerel and such, and whatever else I can't fit somewhere better on this site."]},
    'radio': {'img': '/static/lobster.png',
                'summary': ["Audio works of musical selection, talk, and radio drama, 2009-present.","","","Via KZSU, the radio station of Stanford University."]},
    'resume': {'img': '/static/lobster.png',
                'summary': ["My CV."]},
    'about': {'img': '/static/lobster.png',
                'summary': ["Personal bio, etc, etc."]},
    'projectsanddesign': {'img': '/static/lobster.png',
                'summary': ["Graphic design, non-graphic design, etc.","","","COMING SOON"]},
    'jokes': {'img': '/static/lobster.png',
                'summary': ["Info about an upcoming jokebook with lotsa yuks."]},

}
